import type { ResourceMetadata } from '@pokemon-center/ui-query-builder';

export const pokedexCuratedResources: readonly ResourceMetadata[] = [
	{
		resourceName: 'pokemon',
		displayName: 'Pokémon',
		group: 'Core',
		priority: 100,
		defaultSelectionFieldNames: ['id', 'name'],
		shortcuts: [
			{
				shortcutId: 'type',
				displayName: 'Type',
				fieldPath: ['pokemontypes', 'type', 'name'],
				valueSource: { resourceName: 'type', valueFieldName: 'name' },
			},
			{
				shortcutId: 'ability',
				displayName: 'Ability',
				fieldPath: ['pokemonabilities', 'ability', 'name'],
				valueSource: { resourceName: 'ability', valueFieldName: 'name' },
			},
			{
				shortcutId: 'learnsMove',
				displayName: 'Learns move',
				fieldPath: ['pokemonmoves', 'move', 'name'],
				valueSource: { resourceName: 'move', valueFieldName: 'name' },
			},
			{
				shortcutId: 'hp',
				displayName: 'HP',
				fieldPath: ['base_stat'],
				scope: {
					relationPath: ['pokemonstats'],
					quantifier: 'some',
					pinnedRules: [{ fieldPath: ['stat', 'name'], operatorName: '_eq', value: 'hp' }],
				},
			},
			{
				shortcutId: 'attack',
				displayName: 'Attack',
				fieldPath: ['base_stat'],
				scope: {
					relationPath: ['pokemonstats'],
					quantifier: 'some',
					pinnedRules: [{ fieldPath: ['stat', 'name'], operatorName: '_eq', value: 'attack' }],
				},
			},
			{
				shortcutId: 'defense',
				displayName: 'Defense',
				fieldPath: ['base_stat'],
				scope: {
					relationPath: ['pokemonstats'],
					quantifier: 'some',
					pinnedRules: [{ fieldPath: ['stat', 'name'], operatorName: '_eq', value: 'defense' }],
				},
			},
			{
				shortcutId: 'specialAttack',
				displayName: 'Special Attack',
				fieldPath: ['base_stat'],
				scope: {
					relationPath: ['pokemonstats'],
					quantifier: 'some',
					pinnedRules: [{ fieldPath: ['stat', 'name'], operatorName: '_eq', value: 'special-attack' }],
				},
			},
			{
				shortcutId: 'specialDefense',
				displayName: 'Special Defense',
				fieldPath: ['base_stat'],
				scope: {
					relationPath: ['pokemonstats'],
					quantifier: 'some',
					pinnedRules: [{ fieldPath: ['stat', 'name'], operatorName: '_eq', value: 'special-defense' }],
				},
			},
			{
				shortcutId: 'speed',
				displayName: 'Speed',
				fieldPath: ['base_stat'],
				scope: {
					relationPath: ['pokemonstats'],
					quantifier: 'some',
					pinnedRules: [{ fieldPath: ['stat', 'name'], operatorName: '_eq', value: 'speed' }],
				},
			},
			{
				shortcutId: 'species',
				displayName: 'Species',
				fieldPath: ['pokemonspecy', 'name'],
				valueSource: { resourceName: 'pokemonspecies', valueFieldName: 'name' },
			},
			{ shortcutId: 'name', displayName: 'Name', fieldPath: ['name'] },
			{ shortcutId: 'height', displayName: 'Height', fieldPath: ['height'] },
			{ shortcutId: 'weight', displayName: 'Weight', fieldPath: ['weight'] },
			{ shortcutId: 'baseExperience', displayName: 'Base Experience', fieldPath: ['base_experience'] },
		],
	},
	{
		resourceName: 'move',
		displayName: 'Move',
		group: 'Core',
		priority: 90,
		defaultSelectionFieldNames: ['id', 'name', 'power', 'accuracy'],
		shortcuts: [
			{ shortcutId: 'name', displayName: 'Name', fieldPath: ['name'] },
			{
				shortcutId: 'type',
				displayName: 'Type',
				fieldPath: ['type', 'name'],
				valueSource: { resourceName: 'type', valueFieldName: 'name' },
			},
			{ shortcutId: 'power', displayName: 'Power', fieldPath: ['power'] },
			{ shortcutId: 'accuracy', displayName: 'Accuracy', fieldPath: ['accuracy'] },
			{ shortcutId: 'pp', displayName: 'PP', fieldPath: ['pp'] },
			{ shortcutId: 'priority', displayName: 'Priority', fieldPath: ['priority'] },
			{
				shortcutId: 'contestType',
				displayName: 'Contest Type',
				fieldPath: ['contesttype', 'name'],
				valueSource: { resourceName: 'contesttype', valueFieldName: 'name' },
			},
			{
				shortcutId: 'generation',
				displayName: 'Generation',
				fieldPath: ['generation', 'name'],
				valueSource: { resourceName: 'generation', valueFieldName: 'name' },
			},
			{
				shortcutId: 'learnedBy',
				displayName: 'Learned by',
				fieldPath: ['pokemonmoves', 'pokemon', 'name'],
				valueSource: { resourceName: 'pokemon', valueFieldName: 'name' },
			},
		],
	},
	{
		resourceName: 'ability',
		displayName: 'Ability',
		group: 'Core',
		priority: 80,
		defaultSelectionFieldNames: ['id', 'name'],
		shortcuts: [
			{ shortcutId: 'name', displayName: 'Name', fieldPath: ['name'] },
			{
				shortcutId: 'generation',
				displayName: 'Generation',
				fieldPath: ['generation', 'name'],
				valueSource: { resourceName: 'generation', valueFieldName: 'name' },
			},
			{
				shortcutId: 'pokemon',
				displayName: 'Known by',
				fieldPath: ['pokemonabilities', 'pokemon', 'name'],
				valueSource: { resourceName: 'pokemon', valueFieldName: 'name' },
			},
			{ shortcutId: 'isMainSeries', displayName: 'Main series only', fieldPath: ['is_main_series'] },
		],
	},
	{
		resourceName: 'item',
		displayName: 'Item',
		group: 'Core',
		priority: 70,
		defaultSelectionFieldNames: ['id', 'name'],
		shortcuts: [
			{ shortcutId: 'name', displayName: 'Name', fieldPath: ['name'] },
			{ shortcutId: 'flingPower', displayName: 'Fling Power', fieldPath: ['fling_power'] },
			{
				shortcutId: 'evolvesSpecies',
				displayName: 'Evolves species',
				fieldPath: ['pokemonevolutions', 'pokemonspecy', 'name'],
				valueSource: { resourceName: 'pokemonspecies', valueFieldName: 'name' },
			},
			{
				shortcutId: 'teachesMove',
				displayName: 'Teaches move',
				fieldPath: ['machines', 'move', 'name'],
				valueSource: { resourceName: 'move', valueFieldName: 'name' },
			},
		],
	},
	{
		resourceName: 'type',
		displayName: 'Type',
		group: 'Core',
		priority: 60,
		defaultSelectionFieldNames: ['id', 'name'],
		shortcuts: [
			{ shortcutId: 'name', displayName: 'Name', fieldPath: ['name'] },
			{
				shortcutId: 'generation',
				displayName: 'Generation',
				fieldPath: ['generation', 'name'],
				valueSource: { resourceName: 'generation', valueFieldName: 'name' },
			},
			{
				shortcutId: 'pokemon',
				displayName: 'Pokémon with this type',
				fieldPath: ['pokemontypes', 'pokemon', 'name'],
				valueSource: { resourceName: 'pokemon', valueFieldName: 'name' },
			},
			{
				shortcutId: 'move',
				displayName: 'Move with this type',
				fieldPath: ['moves', 'name'],
				valueSource: { resourceName: 'move', valueFieldName: 'name' },
			},
		],
	},
	{
		resourceName: 'pokemonspecies',
		displayName: 'Species',
		group: 'Classification',
		priority: 100,
		defaultSelectionFieldNames: ['id', 'name'],
		shortcuts: [
			{ shortcutId: 'name', displayName: 'Name', fieldPath: ['name'] },
			{
				shortcutId: 'generation',
				displayName: 'Generation',
				fieldPath: ['generation', 'name'],
				valueSource: { resourceName: 'generation', valueFieldName: 'name' },
			},
			{
				shortcutId: 'growthRate',
				displayName: 'Growth Rate',
				fieldPath: ['growthrate', 'name'],
				valueSource: { resourceName: 'growthrate', valueFieldName: 'name' },
			},
			{
				shortcutId: 'eggGroup',
				displayName: 'Egg Group',
				fieldPath: ['pokemonegggroups', 'egggroup', 'name'],
				valueSource: { resourceName: 'egggroup', valueFieldName: 'name' },
			},
			{ shortcutId: 'isLegendary', displayName: 'Legendary', fieldPath: ['is_legendary'] },
			{ shortcutId: 'isMythical', displayName: 'Mythical', fieldPath: ['is_mythical'] },
			{ shortcutId: 'isBaby', displayName: 'Baby', fieldPath: ['is_baby'] },
			{ shortcutId: 'captureRate', displayName: 'Capture Rate', fieldPath: ['capture_rate'] },
			{ shortcutId: 'baseHappiness', displayName: 'Base Happiness', fieldPath: ['base_happiness'] },
			{ shortcutId: 'hatchCounter', displayName: 'Hatch Counter', fieldPath: ['hatch_counter'] },
		],
	},
	{
		resourceName: 'egggroup',
		displayName: 'Egg Group',
		group: 'Classification',
		priority: 90,
		defaultSelectionFieldNames: ['id', 'name'],
		shortcuts: [
			{ shortcutId: 'name', displayName: 'Name', fieldPath: ['name'] },
			{
				shortcutId: 'species',
				displayName: 'Species in this group',
				fieldPath: ['pokemonegggroups', 'pokemonspecy', 'name'],
				valueSource: { resourceName: 'pokemonspecies', valueFieldName: 'name' },
			},
		],
	},
	{
		resourceName: 'nature',
		displayName: 'Nature',
		group: 'Classification',
		priority: 80,
		defaultSelectionFieldNames: ['id', 'name'],
		shortcuts: [
			{ shortcutId: 'name', displayName: 'Name', fieldPath: ['name'] },
			{
				shortcutId: 'decreasesStat',
				displayName: 'Decreases stat',
				fieldPath: ['stat', 'name'],
				valueSource: { resourceName: 'stat', valueFieldName: 'name' },
			},
			{
				shortcutId: 'increasesStat',
				displayName: 'Increases stat',
				fieldPath: ['StatByIncreasedStatId', 'name'],
				valueSource: { resourceName: 'stat', valueFieldName: 'name' },
			},
		],
	},
	{
		resourceName: 'growthrate',
		displayName: 'Growth Rate',
		group: 'Classification',
		priority: 70,
		defaultSelectionFieldNames: ['id', 'name'],
		shortcuts: [
			{ shortcutId: 'name', displayName: 'Name', fieldPath: ['name'] },
			{ shortcutId: 'formula', displayName: 'Formula', fieldPath: ['formula'] },
			{
				shortcutId: 'species',
				displayName: 'Species with this growth rate',
				fieldPath: ['pokemonspecies', 'name'],
				valueSource: { resourceName: 'pokemonspecies', valueFieldName: 'name' },
			},
		],
	},
	{
		resourceName: 'characteristic',
		displayName: 'Characteristic',
		group: 'Classification',
		priority: 60,
		defaultSelectionFieldNames: ['id', 'gene_mod_5'],
		shortcuts: [
			{
				shortcutId: 'stat',
				displayName: 'Highest stat',
				fieldPath: ['stat', 'name'],
				valueSource: { resourceName: 'stat', valueFieldName: 'name' },
			},
			{ shortcutId: 'geneMod5', displayName: 'Gene Mod 5', fieldPath: ['gene_mod_5'] },
		],
	},
	{
		resourceName: 'region',
		displayName: 'Region',
		group: 'World',
		priority: 100,
		defaultSelectionFieldNames: ['id', 'name'],
		shortcuts: [
			{ shortcutId: 'name', displayName: 'Name', fieldPath: ['name'] },
			{
				shortcutId: 'location',
				displayName: 'Location',
				fieldPath: ['locations', 'name'],
				valueSource: { resourceName: 'location', valueFieldName: 'name' },
			},
			{
				shortcutId: 'generation',
				displayName: 'Generation',
				fieldPath: ['generations', 'name'],
				valueSource: { resourceName: 'generation', valueFieldName: 'name' },
			},
		],
	},
	{
		resourceName: 'location',
		displayName: 'Location',
		group: 'World',
		priority: 90,
		defaultSelectionFieldNames: ['id', 'name'],
		shortcuts: [
			{ shortcutId: 'name', displayName: 'Name', fieldPath: ['name'] },
			{
				shortcutId: 'region',
				displayName: 'Region',
				fieldPath: ['region', 'name'],
				valueSource: { resourceName: 'region', valueFieldName: 'name' },
			},
			{
				shortcutId: 'evolvesSpecies',
				displayName: 'Species that evolves here',
				fieldPath: ['pokemonevolutions', 'pokemonspecy', 'name'],
				valueSource: { resourceName: 'pokemonspecies', valueFieldName: 'name' },
			},
		],
	},
	{
		resourceName: 'encounter',
		displayName: 'Encounter',
		group: 'World',
		priority: 80,
		defaultSelectionFieldNames: ['id', 'pokemon_id', 'min_level', 'max_level'],
		shortcuts: [
			{
				shortcutId: 'pokemon',
				displayName: 'Pokémon',
				fieldPath: ['pokemon', 'name'],
				valueSource: { resourceName: 'pokemon', valueFieldName: 'name' },
			},
			{ shortcutId: 'minLevel', displayName: 'Minimum Level', fieldPath: ['min_level'] },
			{ shortcutId: 'maxLevel', displayName: 'Maximum Level', fieldPath: ['max_level'] },
		],
	},
	{
		resourceName: 'versiongroup',
		displayName: 'Version Group',
		group: 'World',
		priority: 70,
		defaultSelectionFieldNames: ['id', 'name'],
		shortcuts: [
			{ shortcutId: 'name', displayName: 'Name', fieldPath: ['name'] },
			{
				shortcutId: 'generation',
				displayName: 'Generation',
				fieldPath: ['generation', 'name'],
				valueSource: { resourceName: 'generation', valueFieldName: 'name' },
			},
			{
				shortcutId: 'teachesMove',
				displayName: 'Teaches move',
				fieldPath: ['pokemonmoves', 'move', 'name'],
				valueSource: { resourceName: 'move', valueFieldName: 'name' },
			},
			{ shortcutId: 'order', displayName: 'Release Order', fieldPath: ['order'] },
		],
	},
	{
		resourceName: 'generation',
		displayName: 'Generation',
		group: 'World',
		priority: 60,
		defaultSelectionFieldNames: ['id', 'name'],
		shortcuts: [
			{ shortcutId: 'name', displayName: 'Name', fieldPath: ['name'] },
			{
				shortcutId: 'region',
				displayName: 'Region',
				fieldPath: ['region', 'name'],
				valueSource: { resourceName: 'region', valueFieldName: 'name' },
			},
			{
				shortcutId: 'species',
				displayName: 'Introduced species',
				fieldPath: ['pokemonspecies', 'name'],
				valueSource: { resourceName: 'pokemonspecies', valueFieldName: 'name' },
			},
			{
				shortcutId: 'versionGroup',
				displayName: 'Version Group',
				fieldPath: ['versiongroups', 'name'],
				valueSource: { resourceName: 'versiongroup', valueFieldName: 'name' },
			},
		],
	},
	{
		resourceName: 'stat',
		displayName: 'Stat',
		group: 'Mechanics',
		priority: 100,
		defaultSelectionFieldNames: ['id', 'name'],
		shortcuts: [
			{ shortcutId: 'name', displayName: 'Name', fieldPath: ['name'] },
			{ shortcutId: 'gameIndex', displayName: 'Game Index', fieldPath: ['game_index'] },
			{ shortcutId: 'isBattleOnly', displayName: 'Battle-only stat', fieldPath: ['is_battle_only'] },
			{
				shortcutId: 'increasedByNature',
				displayName: 'Increased by nature',
				fieldPath: ['NaturesByIncreasedStatId', 'name'],
				valueSource: { resourceName: 'nature', valueFieldName: 'name' },
			},
			{
				shortcutId: 'decreasedByNature',
				displayName: 'Decreased by nature',
				fieldPath: ['natures', 'name'],
				valueSource: { resourceName: 'nature', valueFieldName: 'name' },
			},
		],
	},
	{
		resourceName: 'machine',
		displayName: 'Machine',
		group: 'Mechanics',
		priority: 90,
		defaultSelectionFieldNames: ['id', 'machine_number'],
		shortcuts: [
			{
				shortcutId: 'move',
				displayName: 'Move',
				fieldPath: ['move', 'name'],
				valueSource: { resourceName: 'move', valueFieldName: 'name' },
			},
			{
				shortcutId: 'item',
				displayName: 'Item',
				fieldPath: ['item', 'name'],
				valueSource: { resourceName: 'item', valueFieldName: 'name' },
			},
			{
				shortcutId: 'versionGroup',
				displayName: 'Version Group',
				fieldPath: ['versiongroup', 'name'],
				valueSource: { resourceName: 'versiongroup', valueFieldName: 'name' },
			},
			{ shortcutId: 'machineNumber', displayName: 'Machine Number', fieldPath: ['machine_number'] },
		],
	},
	{
		resourceName: 'berry',
		displayName: 'Berry',
		group: 'Mechanics',
		priority: 80,
		defaultSelectionFieldNames: ['id', 'name'],
		shortcuts: [
			{ shortcutId: 'name', displayName: 'Name', fieldPath: ['name'] },
			{
				shortcutId: 'naturalGiftType',
				displayName: 'Natural Gift Type',
				fieldPath: ['type', 'name'],
				valueSource: { resourceName: 'type', valueFieldName: 'name' },
			},
			{ shortcutId: 'naturalGiftPower', displayName: 'Natural Gift Power', fieldPath: ['natural_gift_power'] },
			{ shortcutId: 'growthTime', displayName: 'Growth Time', fieldPath: ['growth_time'] },
			{
				shortcutId: 'item',
				displayName: 'Item',
				fieldPath: ['item', 'name'],
				valueSource: { resourceName: 'item', valueFieldName: 'name' },
			},
			{ shortcutId: 'size', displayName: 'Size', fieldPath: ['size'] },
		],
	},
	{
		resourceName: 'contesttype',
		displayName: 'Contest Type',
		group: 'Mechanics',
		priority: 70,
		defaultSelectionFieldNames: ['id', 'name'],
		shortcuts: [
			{ shortcutId: 'name', displayName: 'Name', fieldPath: ['name'] },
			{
				shortcutId: 'move',
				displayName: 'Move with this contest type',
				fieldPath: ['moves', 'name'],
				valueSource: { resourceName: 'move', valueFieldName: 'name' },
			},
		],
	},
];
