export const pokedexFieldLabels: Readonly<Record<string, string>> = {
	BerryflavorByLikesFlavorId: 'Liked Flavor',
	ContestcombosBySecondMoveId: 'Second Move Combos',
	ItemByHeldItemId: 'Held Item',
	LanguageByLocalLanguageId: 'Language',
	LanguagenamesByLocalLanguageId: 'Names In This Language',
	MoveBySecondMoveId: 'Second Move',
	NaturesByIncreasedStatId: 'Natures Increasing This Stat',
	NaturesByLikesFlavorId: 'Natures Liking This Flavor',
	PokemonevolutionsByHeldItemId: 'Evolutions Requiring This Item',
	PokemonevolutionsByPartySpeciesId: 'Evolutions Requiring This Species In Party',
	PokemonevolutionsByPartyTypeId: 'Evolutions Requiring This Type In Party',
	PokemonevolutionsByTradeSpeciesId: 'Evolutions Requiring Trading For This Species',
	PokemonspecyByPartySpeciesId: 'Party Species',
	PokemonspecyByTradeSpeciesId: 'Trade Species',
	StatByIncreasedStatId: 'Increased Stat',
	SupercontestcombosBySecondMoveId: 'Second Move Combos',
	TypeByPartyTypeId: 'Party Type',
	TypeByTargetTypeId: 'Target Type',
	TypeefficaciesByTargetTypeId: 'Efficacies Against This Type',
	TypeefficacypastsByTargetTypeId: 'Past Efficacies Against This Type',
	abilities: 'Abilities',
	ability: 'Ability',
	ability_change_id: 'Ability Change',
	ability_id: 'Ability',
	abilitychange: 'Ability Change',
	abilitychangeeffecttexts: 'Ability Change Effect Text',
	abilitychanges: 'Changes',
	abilityeffecttexts: 'Effect Text',
	abilityflavortexts: 'Flavor Text',
	abilitynames: 'Names',
	accuracy: 'Accuracy',
	ailment_chance: 'Ailment Chance',
	appeal: 'Appeal',
	awesome_name: 'Awesome Name',
	baby_trigger_item_id: 'Baby Trigger Item',
	base_experience: 'Base Experience',
	base_form: 'Base Form',
	base_form_id: 'Base Form',
	base_happiness: 'Base Happiness',
	base_score: 'Base Score',
	base_stat: 'Base Stat',
	baseformid: 'Base Form',
	berries: 'Berries',
	berry: 'Berry',
	berry_firmness_id: 'Berry Firmness',
	berry_flavor_id: 'Berry Flavor',
	berry_id: 'Berry',
	berryfirmness: 'Firmness',
	berryfirmnessnames: 'Berry Firmness Names',
	berryflavor: 'Berry Flavor',
	berryflavormaps: 'Flavor Maps',
	berryflavornames: 'Berry Flavor Names',
	berryflavors: 'Berry Flavors',
	capture_rate: 'Capture Rate',
	change: 'Change',
	characteristic: 'Characteristic',
	characteristic_id: 'Characteristic',
	characteristicdescriptions: 'Descriptions',
	characteristics: 'Characteristics',
	color: 'Color',
	contest_effect_id: 'Contest Effect',
	contest_type_id: 'Contest Type',
	contestcombos: 'Contest Combos',
	contesteffect: 'Contest Effect',
	contesteffecteffecttexts: 'Contest Effect Text',
	contesteffectflavortexts: 'Contest Effect Flavor Text',
	contesttype: 'Contest Type',
	contesttypenames: 'Names',
	cries: 'Cries',
	crit_rate: 'Crit Rate',
	currency: 'Currency',
	currency_id: 'Currency',
	currencynames: 'Currency Names',
	damage_factor: 'Damage Factor',
	damage_type_id: 'Damage Type',
	decreased_stat_id: 'Decreased Stat',
	description: 'Description',
	drain: 'Drain',
	effect: 'Effect',
	effort: 'Effort',
	egg_group_id: 'Egg Group',
	egggroup: 'Egg Group',
	egggroupnames: 'Egg Group Names',
	encounter: 'Encounter',
	encounter_condition_id: 'Encounter Condition',
	encounter_condition_value_id: 'Encounter Condition Value',
	encounter_id: 'Encounter',
	encounter_method_id: 'Encounter Method',
	encounter_slot_id: 'Encounter Slot',
	encountercondition: 'Encounter Condition',
	encounterconditionnames: 'Encounter Condition Names',
	encounterconditionvalue: 'Encounter Condition Value',
	encounterconditionvaluemaps: 'Condition Value Maps',
	encounterconditionvaluenames: 'Encounter Condition Value Names',
	encounterconditionvalues: 'Encounter Condition Values',
	encountermethod: 'Encounter Method',
	encountermethodnames: 'Encounter Method Names',
	encounters: 'Encounters',
	encounterslot: 'Slot',
	encounterslots: 'Encounter Slots',
	evolution_chain_id: 'Evolution Chain',
	evolution_item_id: 'Evolution Item',
	evolution_trigger_id: 'Evolution Trigger',
	evolutionchain: 'Evolution Chain',
	evolutionchains: 'Evolution Chains',
	evolutiontrigger: 'Evolution Trigger',
	evolutiontriggernames: 'Evolution Trigger Names',
	evolved_form_id: 'Evolved Form',
	evolved_species_id: 'Evolved Species',
	evolves_from_species_id: 'Evolves From Species',
	experience: 'Experience',
	experiences: 'Experiences',
	first_move_id: 'First Move',
	flavor: 'Flavor',
	flavor_text: 'Flavor Text',
	flinch_chance: 'Flinch Chance',
	fling_power: 'Fling Power',
	form_name: 'Form Name',
	form_order: 'Form Order',
	form_trigger_id: 'Form Trigger',
	forms_switchable: 'Forms Switchable',
	formula: 'Formula',
	game_index: 'Game Index',
	gender: 'Gender',
	gender_id: 'Gender',
	gender_rate: 'Gender Rate',
	gene_mod_5: 'Gene Mod 5',
	generation: 'Generation',
	generation_id: 'Generation',
	generationnames: 'Names',
	generations: 'Generations',
	genus: 'Genus',
	growth_rate_id: 'Growth Rate',
	growth_time: 'Growth Time',
	growthrate: 'Growth Rate',
	growthratedescriptions: 'Descriptions',
	has_gender_differences: 'Has Gender Differences',
	hatch_counter: 'Hatch Counter',
	hates_flavor_id: 'Hates Flavor',
	healing: 'Healing',
	height: 'Height',
	held_item_id: 'Held Item',
	high_hp_preference: 'High HP Preference',
	id: 'ID',
	increased_stat_id: 'Increased Stat',
	is_baby: 'Is Baby',
	is_battle_only: 'Is Battle Only',
	is_default: 'Is Default',
	is_hidden: 'Is Hidden',
	is_legendary: 'Is Legendary',
	is_main_series: 'Is Main Series',
	is_mega: 'Is Mega',
	is_mythical: 'Is Mythical',
	iso3166: 'ISO 3166',
	iso639: 'ISO 639',
	item: 'Item',
	item_attribute_id: 'Item Attribute',
	item_category_id: 'Item Category',
	item_fling_effect_id: 'Item Fling Effect',
	item_id: 'Item',
	item_pocket_id: 'Item Pocket',
	itemattribute: 'Item Attribute',
	itemattributedescriptions: 'Item Attribute Descriptions',
	itemattributemaps: 'Attribute Maps',
	itemattributenames: 'Item Attribute Names',
	itemcategories: 'Item Categories',
	itemcategory: 'Category',
	itemcategorynames: 'Item Category Names',
	itemeffecttexts: 'Effect Text',
	itemflavortexts: 'Flavor Text',
	itemflingeffect: 'Fling Effect',
	itemflingeffecteffecttexts: 'Item Fling Effect Text',
	itemgameindices: 'Game Indices',
	itemnames: 'Names',
	itempocket: 'Pocket',
	itempocketnames: 'Item Pocket Names',
	itemprices: 'Prices',
	items: 'Items',
	itemsprites: 'Sprites',
	jam: 'Jam',
	known_move_id: 'Known Move',
	known_move_type_id: 'Known Move Type',
	language: 'Language',
	language_id: 'Language',
	languagenames: 'Names',
	level: 'Level',
	likes_flavor_id: 'Likes Flavor',
	local_language_id: 'Local Language',
	location: 'Location',
	location_area_id: 'Location Area',
	location_id: 'Location',
	locationarea: 'Location Area',
	locationareaencounterrates: 'Location Area Encounter Rates',
	locationareanames: 'Location Area Names',
	locationareas: 'Areas',
	locationgameindices: 'Game Indices',
	locationnames: 'Names',
	locations: 'Locations',
	low_hp_preference: 'Low HP Preference',
	machine_number: 'Machine Number',
	machines: 'Machines',
	mastery: 'Mastery',
	max_change: 'Max Change',
	max_harvest: 'Max Harvest',
	max_hits: 'Max Hits',
	max_level: 'Max Level',
	max_turns: 'Max Turns',
	min_affection: 'Min Affection',
	min_beauty: 'Min Beauty',
	min_damage_taken: 'Min Damage Taken',
	min_happiness: 'Min Happiness',
	min_hits: 'Min Hits',
	min_level: 'Min Level',
	min_move_count: 'Min Move Count',
	min_steps: 'Min Steps',
	min_turns: 'Min Turns',
	move: 'Move',
	move_attribute_id: 'Move Attribute',
	move_battle_style_id: 'Move Battle Style',
	move_damage_class_id: 'Move Damage Class',
	move_effect_chance: 'Move Effect Chance',
	move_effect_change_id: 'Move Effect Change',
	move_effect_id: 'Move Effect',
	move_id: 'Move',
	move_learn_method_id: 'Move Learn Method',
	move_meta_ailment_id: 'Move Meta Ailment',
	move_meta_category_id: 'Move Meta Category',
	move_target_id: 'Move Target',
	moveattribute: 'Move Attribute',
	moveattributedescriptions: 'Move Attribute Descriptions',
	moveattributemaps: 'Attribute Maps',
	moveattributenames: 'Move Attribute Names',
	movebattlestyle: 'Move Battle Style',
	movebattlestylenames: 'Move Battle Style Names',
	movechanges: 'Changes',
	movedamageclass: 'Move Damage Class',
	movedamageclassdescriptions: 'Move Damage Class Descriptions',
	movedamageclassnames: 'Move Damage Class Names',
	moveeffect: 'Effect',
	moveeffectchange: 'Move Effect Change',
	moveeffectchangeeffecttexts: 'Move Effect Change Effect Text',
	moveeffectchanges: 'Move Effect Changes',
	moveeffecteffecttexts: 'Move Effect Text',
	moveflavortexts: 'Flavor Text',
	movelearnmethod: 'Move Learn Method',
	movelearnmethoddescriptions: 'Move Learn Method Descriptions',
	movelearnmethodnames: 'Move Learn Method Names',
	movemeta: 'Meta',
	movemetaailment: 'Move Meta Ailment',
	movemetaailmentnames: 'Move Meta Ailment Names',
	movemetacategory: 'Move Meta Category',
	movemetacategorydescriptions: 'Move Meta Category Descriptions',
	movemetastatchanges: 'Meta Stat Changes',
	movemetum: 'Meta',
	movenames: 'Names',
	moves: 'Moves',
	movetarget: 'Move Target',
	movetargetdescriptions: 'Move Target Descriptions',
	movetargetnames: 'Move Target Names',
	name: 'Name',
	natural_gift_power: 'Natural Gift Power',
	natural_gift_type_id: 'Natural Gift Type',
	nature: 'Nature',
	nature_id: 'Nature',
	naturebattlestylepreferences: 'Battle Style Preferences',
	naturenames: 'Names',
	naturepokeathlonstats: 'Pokéathlon Stats',
	natures: 'Natures',
	near_special_rock: 'Near Special Rock',
	needs_multiplayer: 'Needs Multiplayer',
	needs_overworld_rain: 'Needs Overworld Rain',
	official: 'Official',
	order: 'Order',
	pal_park_area_id: 'Pal Park Area',
	palparkarea: 'Pal Park Area',
	palparkareanames: 'Pal Park Area Names',
	palparks: 'Pal Parks',
	party_species_id: 'Party Species',
	party_type_id: 'Party Type',
	pokeathlon_stat_id: 'Pokéathlon Stat',
	pokeathlonstat: 'Pokéathlon Stat',
	pokeathlonstatnames: 'Pokéathlon Stat Names',
	pokedex: 'Pokédex',
	pokedex_id: 'Pokédex',
	pokedex_number: 'Pokédex Number',
	pokedexdescriptions: 'Pokédex Descriptions',
	pokedexes: 'Pokédexes',
	pokedexnames: 'Pokédex Names',
	pokedexversiongroups: 'Pokédex Version Groups',
	pokemon: 'Pokémon',
	pokemon_color_id: 'Pokémon Color',
	pokemon_form_id: 'Pokémon Form',
	pokemon_habitat_id: 'Pokémon Habitat',
	pokemon_id: 'Pokémon',
	pokemon_name: 'Pokémon Name',
	pokemon_shape_id: 'Pokémon Shape',
	pokemon_species_id: 'Pokémon Species',
	pokemonabilities: 'Abilities',
	pokemonabilitypasts: 'Past Abilities',
	pokemoncolor: 'Color',
	pokemoncolornames: 'Color Names',
	pokemoncries: 'Cries',
	pokemondexnumbers: 'Dex Numbers',
	pokemonegggroups: 'Egg Groups',
	pokemonevolutions: 'Evolutions',
	pokemonevolutionsByKnownMoveId: 'Evolutions Requiring This Known Move',
	pokemonevolutionsByUsedMoveId: 'Evolutions Triggered By Using This Move',
	pokemonevolutionsbyevolvedformid: 'Evolutions Into This Form',
	pokemonform: 'Form',
	pokemonformconditions: 'Form Conditions',
	pokemonformgenerations: 'Form Generations',
	pokemonformnames: 'Form Names',
	pokemonforms: 'Forms',
	pokemonformsprites: 'Form Sprites',
	pokemonformtrigger: 'Form Trigger',
	pokemonformtypes: 'Form Types',
	pokemongameindices: 'Game Indices',
	pokemonhabitat: 'Habitat',
	pokemonhabitatnames: 'Habitat Names',
	pokemonitems: 'Items',
	pokemonmoves: 'Moves',
	pokemons: 'Pokémon',
	pokemonshape: 'Shape',
	pokemonshapenames: 'Shape Names',
	pokemonspecies: 'Species',
	pokemonspeciesdescriptions: 'Descriptions',
	pokemonspeciesflavortexts: 'Flavor Text',
	pokemonspeciesnames: 'Names',
	pokemonspecy: 'Species',
	pokemonsprites: 'Sprites',
	pokemonstatpasts: 'Past Stats',
	pokemonstats: 'Stats',
	pokemontypepasts: 'Past Types',
	pokemontypes: 'Types',
	potency: 'Potency',
	power: 'Power',
	pp: 'PP',
	priority: 'Priority',
	purchase_price: 'Purchase Price',
	rarity: 'Rarity',
	rate: 'Rate',
	region: 'Region',
	region_id: 'Region',
	regionnames: 'Names',
	relative_physical_stats: 'Relative Physical Stats',
	second_move_id: 'Second Move',
	sell_price: 'Sell Price',
	short_effect: 'Short Effect',
	size: 'Size',
	slot: 'Slot',
	smoothness: 'Smoothness',
	soil_dryness: 'Soil Dryness',
	sprites: 'Sprites',
	stat: 'Stat',
	stat_chance: 'Stat Chance',
	stat_id: 'Stat',
	statnames: 'Names',
	stats: 'Stats',
	super_contest_effect_id: 'Super Contest Effect',
	supercontestcombos: 'Super Contest Combos',
	supercontesteffect: 'Super Contest Effect',
	supercontesteffectflavortexts: 'Super Contest Effect Flavor Text',
	target_type_id: 'Target Type',
	time_of_day: 'Time Of Day',
	trade_species_id: 'Trade Species',
	turn_upside_down: 'Turn Upside Down',
	type: 'Type',
	type_id: 'Type',
	typeefficacies: 'Efficacies',
	typeefficacypasts: 'Past Efficacies',
	typegameindices: 'Game Indices',
	typenames: 'Names',
	types: 'Types',
	used_move_id: 'Used Move',
	usedmove: 'Used Move',
	version: 'Version',
	version_group_id: 'Version Group',
	version_id: 'Version',
	versiongroup: 'Version Group',
	versiongroupmovelearnmethods: 'Move Learn Methods',
	versiongroupregions: 'Regions',
	versiongroups: 'Version Groups',
	versionnames: 'Version Names',
	versions: 'Versions',
	weight: 'Weight',
};
