export const pokedexResourceLabels: Readonly<Record<string, string>> = {
	ability: 'Ability',
	abilitychange: 'Ability Change',
	abilitychangeeffecttext: 'Ability Change Effect Text',
	abilityeffecttext: 'Ability Effect Text',
	abilityflavortext: 'Ability Flavor Text',
	abilityname: 'Ability Name',
	berry: 'Berry',
	berryfirmness: 'Berry Firmness',
	berryfirmnessname: 'Berry Firmness Name',
	berryflavor: 'Berry Flavor',
	berryflavormap: 'Berry Flavor Map',
	berryflavorname: 'Berry Flavor Name',
	characteristic: 'Characteristic',
	characteristicdescription: 'Characteristic Description',
	contestcombo: 'Contest Combo',
	contesteffect: 'Contest Effect',
	contesteffecteffecttext: 'Contest Effect Text',
	contesteffectflavortext: 'Contest Effect Flavor Text',
	contesttype: 'Contest Type',
	contesttypename: 'Contest Type Name',
	currency: 'Currency',
	currencyname: 'Currency Name',
	egggroup: 'Egg Group',
	egggroupname: 'Egg Group Name',
	encounter: 'Encounter',
	encountercondition: 'Encounter Condition',
	encounterconditionname: 'Encounter Condition Name',
	encounterconditionvalue: 'Encounter Condition Value',
	encounterconditionvaluemap: 'Encounter Condition Value Map',
	encounterconditionvaluename: 'Encounter Condition Value Name',
	encountermethod: 'Encounter Method',
	encountermethodname: 'Encounter Method Name',
	encounterslot: 'Encounter Slot',
	evolutionchain: 'Evolution Chain',
	evolutiontrigger: 'Evolution Trigger',
	evolutiontriggername: 'Evolution Trigger Name',
	experience: 'Experience',
	gender: 'Gender',
	generation: 'Generation',
	generationname: 'Generation Name',
	growthrate: 'Growth Rate',
	growthratedescription: 'Growth Rate Description',
	item: 'Item',
	itemattribute: 'Item Attribute',
	itemattributedescription: 'Item Attribute Description',
	itemattributemap: 'Item Attribute Map',
	itemattributename: 'Item Attribute Name',
	itemcategory: 'Item Category',
	itemcategoryname: 'Item Category Name',
	itemeffecttext: 'Item Effect Text',
	itemflavortext: 'Item Flavor Text',
	itemflingeffect: 'Item Fling Effect',
	itemflingeffecteffecttext: 'Item Fling Effect Text',
	itemgameindex: 'Item Game Index',
	itemname: 'Item Name',
	itempocket: 'Item Pocket',
	itempocketname: 'Item Pocket Name',
	itemprice: 'Item Price',
	itemsprites: 'Item Sprites',
	language: 'Language',
	languagename: 'Language Name',
	location: 'Location',
	locationarea: 'Location Area',
	locationareaencounterrate: 'Location Area Encounter Rate',
	locationareaname: 'Location Area Name',
	locationgameindex: 'Location Game Index',
	locationname: 'Location Name',
	machine: 'Machine',
	move: 'Move',
	moveattribute: 'Move Attribute',
	moveattributedescription: 'Move Attribute Description',
	moveattributemap: 'Move Attribute Map',
	moveattributename: 'Move Attribute Name',
	movebattlestyle: 'Move Battle Style',
	movebattlestylename: 'Move Battle Style Name',
	movechange: 'Move Change',
	movedamageclass: 'Move Damage Class',
	movedamageclassdescription: 'Move Damage Class Description',
	movedamageclassname: 'Move Damage Class Name',
	moveeffect: 'Move Effect',
	moveeffectchange: 'Move Effect Change',
	moveeffectchangeeffecttext: 'Move Effect Change Text',
	moveeffecteffecttext: 'Move Effect Text',
	moveflavortext: 'Move Flavor Text',
	movelearnmethod: 'Move Learn Method',
	movelearnmethoddescription: 'Move Learn Method Description',
	movelearnmethodname: 'Move Learn Method Name',
	movemeta: 'Move Meta',
	movemetaailment: 'Move Meta Ailment',
	movemetaailmentname: 'Move Meta Ailment Name',
	movemetacategory: 'Move Meta Category',
	movemetacategorydescription: 'Move Meta Category Description',
	movemetastatchange: 'Move Meta Stat Change',
	movename: 'Move Name',
	movetarget: 'Move Target',
	movetargetdescription: 'Move Target Description',
	movetargetname: 'Move Target Name',
	nature: 'Nature',
	naturebattlestylepreference: 'Nature Battle Style Preference',
	naturename: 'Nature Name',
	naturepokeathlonstat: 'Nature Pokéathlon Stat',
	palpark: 'Pal Park',
	palparkarea: 'Pal Park Area',
	palparkareaname: 'Pal Park Area Name',
	pokeathlonstat: 'Pokéathlon Stat',
	pokeathlonstatname: 'Pokéathlon Stat Name',
	pokedex: 'Pokédex',
	pokedexdescription: 'Pokédex Description',
	pokedexname: 'Pokédex Name',
	pokedexversiongroup: 'Pokédex Version Group',
	pokemon: 'Pokémon',
	pokemonability: 'Pokémon Ability',
	pokemonabilitypast: 'Past Ability',
	pokemoncolor: 'Pokémon Color',
	pokemoncolorname: 'Pokémon Color Name',
	pokemoncries: 'Pokémon Cries',
	pokemondexnumber: 'Pokémon Dex Number',
	pokemonegggroup: 'Pokémon Egg Group',
	pokemonevolution: 'Pokémon Evolution',
	pokemonform: 'Pokémon Form',
	pokemonformcondition: 'Pokémon Form Condition',
	pokemonformflavortext: 'Pokémon Form Flavor Text',
	pokemonformgeneration: 'Pokémon Form Generation',
	pokemonformname: 'Pokémon Form Name',
	pokemonformsprites: 'Pokémon Form Sprites',
	pokemonformtrigger: 'Pokémon Form Trigger',
	pokemonformtype: 'Pokémon Form Type',
	pokemongameindex: 'Pokémon Game Index',
	pokemonhabitat: 'Pokémon Habitat',
	pokemonhabitatname: 'Pokémon Habitat Name',
	pokemonitem: 'Pokémon Item',
	pokemonmove: 'Pokémon Move',
	pokemonshape: 'Pokémon Shape',
	pokemonshapename: 'Pokémon Shape Name',
	pokemonspecies: 'Species',
	pokemonspeciesdescription: 'Pokémon Species Description',
	pokemonspeciesflavortext: 'Pokémon Species Flavor Text',
	pokemonspeciesname: 'Pokémon Species Name',
	pokemonsprites: 'Pokémon Sprites',
	pokemonstat: 'Pokémon Stat',
	pokemonstatpast: 'Past Stat',
	pokemontype: 'Pokémon Type',
	pokemontypepast: 'Past Type',
	region: 'Region',
	regionname: 'Region Name',
	stat: 'Stat',
	statname: 'Stat Name',
	supercontestcombo: 'Super Contest Combo',
	supercontesteffect: 'Super Contest Effect',
	supercontesteffectflavortext: 'Super Contest Effect Flavor Text',
	type: 'Type',
	typeefficacy: 'Type Efficacy',
	typeefficacypast: 'Past Type Efficacy',
	typegameindex: 'Type Game Index',
	typename: 'Type Name',
	version: 'Version',
	versiongroup: 'Version Group',
	versiongroupmovelearnmethod: 'Version Group Move Learn Method',
	versiongroupregion: 'Version Group Region',
	versionname: 'Version Name',
};
